name: skp_port
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  auto_size_text: ^3.0.0
  cloud_firestore: ^4.12.1
  cupertino_icons: ^1.0.6
  firebase_auth: ^4.12.0
  firebase_core: ^2.20.0
  flutter_riverpod: ^2.4.5
  flutter_screenutil: ^5.9.0
  get_it: ^7.6.4
  injectable: ^2.3.2
  intl: ^0.18.1
  json_annotation: ^4.8.1
  material_design_icons_flutter: ^7.0.7296
  riverpod_annotation: ^2.3.0
  url_launcher: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.6
  flutter_lints: ^3.0.0
  injectable_generator: ^2.4.1
  json_serializable: ^6.7.1
  riverpod_generator: ^2.3.5
  riverpod_lint: ^2.3.3

flutter:
  uses-material-design: true

  # assets:
  #   - images/a_dot_burr.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

flutter_intl:
  enabled: true